### PR TITLE
Added option to copy a file before it is deleted after being imported

### PR DESCRIPTION
**Pull request by Gabisonfire**
Added option to copy a file before it is deleted after being imported following @Cornelicorn 's recommendations.

### CODE REVIEW

**Comment by Gabisonfire** [comment]
Argh, forgot to CTRL+S -_-

**Comment by Cornelicorn** [comment]
See #416

**Comment by jendib** [comment]
@Cornelicorn Considering you did the last PR on this importer script, everything seems alright to you?

**Comment by Cornelicorn** [comment]
> @Cornelicorn Considering you did the last PR on this importer script, everything seems alright to you?

Everything seems good, already took the liberty to suggest some changes on #416. Also approved the changes here.

**Comment by jendib** [comment]
Great, thanks!

**Pull request merged**
