### PR TITLE
Specify document search parameter as HTTP params

### PR DESCRIPTION
**Pull request by archiloque**
An implementation for https://github.com/sismics/docs/issues/720 , feedbacks are welcome.

I'm still doing some tests.

Notes so far:
- I tried to share the code between the two ways of passing parameters, I moved the related code to `docs-web/src/main/java/com/sismics/docs/rest/util/DocumentSearchCriteriaUtil.java` to avoid making a mess of `docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java`, at the end it's not too much new code.
- Moved `docs-web/src/main/java/com/sismics/docs/rest/util/TagUtil.java` from `docs-core` because it was not used outside of `docs-web`. 
- I've renamed the simple search as simple search, so it's easier to distinguish between simple and full.
- Specified some parameters as optionals, even with other end points.
- Cleaning some code duplication between `get` and `list` for documents when generating the responses, as a consequence I added the `file_id` field to the `get` response because it was missing there but was in the `list` one, which did not make sense.

I wonder if all the cases exposed through the "textual API" make sense for a programmatic one, for example:
- `at` can be replaced by `before` and an `after`, should it be available?
- exposing several date formats, maybe the `yyyy-MM-dd` one should be enough?

What's your opinion ?

### CODE REVIEW

**Comment by jendib** [comment]
Looks good.

I agree that "at" and date formats other than "yyyy-MM-dd" could be removed to simplifiy. It should be the role of the caller to do those things with "before" and "after".

**Comment by archiloque** [comment]
@jendib thanks, I've updated the code accordingly

**Comment by jendib** [comment]
@archiloque Is this ready to merge?

**Comment by archiloque** [comment]
@jendib yes, I've done some integration tests and it seems to work

**Pull request merged**
