### PR TITLE
Adjust bcrypt and improve readme

### PR DESCRIPTION
**Pull request by Vec7or**
- Since I did not find the available environment variables when I tried to setup the application I thought it might be helpful for others if they were included inside the README.
- Additionally I added two basic examples for usage with docker-compose

### CODE REVIEW

**Comment by Vec7or** [comment]
I adjusted the bcrypt-library according to issue #488.

**Comment by jendib** [comment]
you should have done another PR for this, but it's fine.
Did you check that old password are valid with the new lib?

**Comment by Vec7or** [comment]
Man you are fast :+1:  i have just commented in the issue.

**Comment by Vec7or** [comment]
> you should have done another PR for this, but it's fine.
> Did you check that old password are valid with the new lib?

Should I delete it and make two seperate PR's? I just thought that the readme adjustments were nothing major and therefore created just one.

**Comment by jendib** [comment]
It's fine don't bother. I will check everything in one go when I have some free time.

**Pull request merged**
