### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by AkshayraviC09YC47**

### CODE REVIEW

**Comment by AkshayraviC09YC47** [comment]
Hello maintainer, im a security researcher, i have reported few security vulnerabilities that i have found on **sismics/doc** on [https://huntr.dev/](url), can you please check that, thanks😇

**Comment by vmario89** [comment]
https://huntr.dev/repos/sismics/docs/ nothing there .... ?

**Comment by AkshayraviC09YC47** [comment]
Hello maintainer i have reported few security vulnerabilities of sismics/doc via [huntr.dev](https://huntr.dev/) please check those reports, the hunter team admin mentioned that they were not able to reach you

Here are the report links:
https://huntr.dev/bounties/504a3cfb-5c89-4964-9dff-755c49e5b190/
https://huntr.dev/bounties/2be10ae3-cd49-4446-9b24-931a2c338006/
https://huntr.dev/bounties/8cf26b11-c29c-4a22-947e-befecfabd2df/
https://huntr.dev/bounties/7b78cf91-3bd8-477e-b695-ae9228b785ba/

@vmario89 @jendib

**Comment by SamTV12345** [comment]
Why was this pr even closed? You should never say that an account is registered for this email address.

**Comment by jendib** [comment]
It's unrelated to the original PR, an separate issue was opened.

**Pull request closed without merging**
