### PR TITLE
make encryption cipher selectable

### PR DESCRIPTION
**Pull request by nixn**
via the system property `teedy.cipher`. "NULL" is allowed explicitly,
meaning no file encryption will take place. it works around the security settings
by using javax.crypto.NullCipher directly, so it does not harm other security in any way.

All already created files are readable by a fallback system (falling back to the "legacy" cipher). For all new files a new file is created: fileId + "_cipher", where the cipher used is stored. So one can update the "default" cipher (which currently is the same as the legacy cipher) without sacrificing all the documents already stored.

### CODE REVIEW

**Comment by nixn** [comment]
The PR is based off the tag v1.8, I did not check if it is mergeable with the current state of code. If you accept the PR, please check yourself.

**Comment by Vec7or** [comment]
If this feature where to be implemented wouldn't it be better to include the Cipher into the database-table `t_file`? That way no additional files would need to be stored and a database-migration could be added to simply set the field to default (`AES/CTR/NOPADDING`) for all existing files.

In principle I am all for that feature since there are some use-cases where encryption is not necessary. But since #446 was closed very quickly I suspect it might be considered out of scope by the maintainers.

**Comment by jendib** [comment]
I agree with @Vec7or , I don't see the point of storing it in a separate file.
A DB column with the current cipher as default seems more appropriate.

**Comment by nixn** [comment]
I see, that the DB would be a more appropriate place for this information. It was a first and fast shot at this feature, I didn't even check the current DB structure, just implemented it the first encountered and easy looking way. But much of the code written would be needed for the DB-way too, so if you want to integrate that feature, one (perhaps me) could re-use those parts of the PR code. I was only looking at your code for less than 2 hours in total, mostly while implementing already, beginning two days ago...

Still the question resides: Do you want to integrate such a selectable-cipher feature?

**Comment by jendib** [comment]
If there is a PR and it's an optional feature for existing users, sure.

**Pull request closed without merging**
